# -*- coding: utf-8 -*-
"""MoredataultralyticsYOLOv5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZGKBAM5LPR1z1G9p7B-b59o9gP8M0NG5
"""

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir('/content/gdrive/My Drive/yolov5')

import os
import torch
from IPython.display import Image, clear_output 
print('PyTorch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

!pwd

# Commented out IPython magic to ensure Python compatibility.
# Tensorboard (optional)
# %load_ext tensorboard
# %tensorboard --logdir runs

# Commented out IPython magic to ensure Python compatibility.
# Weights & Biases (optional)
# %pip install -q wandb  
!wandb login  # use 'wandb disabled' or 'wandb enabled' to disable or enable

!ls -lrt

!ls -lrt

!pwd

# Train YOLOv3 on COCO128 for 3 epochs
!python train.py --img 400 --batch 16 --epochs 500 --data pothole.yaml --cfg models/yolov5m.yaml --name moredatayolov5

"""# 4. Visualize"""

Image(filename='runs/train/pt/train_batch1.jpg', width=400)  # train batch 0 mosaics and labels
Image(filename='runs/train/pt/test_batch1_labels.jpg', width=400)  # test batch 0 labels
Image(filename='runs/train/pt/test_batch1_pred.jpg', width=400)  # test batch 0 predictions

from utils.plots import plot_results 
plot_results(save_dir='runs/train/pt')  # plot all results*.txt as results.png
Image(filename='runs/train/pt/results.png', width=400)

!python detect.py --source /content/gdrive/MyDrive/potholenew/ --img 416 --weights /content/gdrive/MyDrive/yolov5/runs/train/moredatayolov5/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes4/images/ --img 416 --weights /content/gdrive/MyDrive/yolov5/runs/train/moredatayolov5/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes4/images/ --img 416 --weights /content/gdrive/MyDrive/yolov5/runs/train/moredatayolov5/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes3/images/test/ --img 416 --weights /content/gdrive/MyDrive/yolov5/runs/train/moredatayolov5/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes3/images/test/ --img 416 --weights /content/gdrive/MyDrive/yolov5/runs/train/moredatayolov5/weights/best.pt