# -*- coding: utf-8 -*-
"""ultralyticsYOLOv3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eBNcQ0HztxcRD-DE1UrTWRA1i6L1XMZv
"""

from google.colab import drive
drive.mount('/content/gdrive')



import os
os.chdir('/content/gdrive/My Drive/moredatayolov3')

import os
import torch
from IPython.display import Image, clear_output 
print('PyTorch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

!pwd

# Commented out IPython magic to ensure Python compatibility.
# Tensorboard (optional)
# %load_ext tensorboard
# %tensorboard --logdir runs

# Commented out IPython magic to ensure Python compatibility.
# Weights & Biases (optional)
# %pip install -q wandb  
!wandb login  # use 'wandb disabled' or 'wandb enabled' to disable or enable

!python train.py --img 416 --batch 16 --epochs 1000 --data pothole.yaml --cfg models/yolov3.yaml --name potholeyolovfinal3

# Train YOLOv3 on COCO128 for 3 epochs
#
!python train.py --img 416 --batch 16 --epochs 300 --data pothole.yaml --cfg models/yolov3.yaml --name lastmorepothole3

"""# 4. Visualize"""

Image(filename='runs/train/lastmorepothole3/train_batch1.jpg', width=400)  # train batch 0 mosaics and labels
Image(filename='runs/train/lastmorepothole3/test_batch1_labels.jpg', width=400)  # test batch 0 labels
Image(filename='runs/train/lastmorepothole3/test_batch1_pred.jpg', width=400)  # test batch 0 predictions

!python train.py --img 416 --batch 16 --epochs 1000 --data pothole.yaml --cfg models/yolov3.yaml --name potholeyolovfinal3

from utils.plots import plot_results 
plot_results(save_dir='runs/train/potholeyolovfinal32')  # plot all results*.txt as results.png
Image(filename='runs/train/potholeyolovfinal32/results.png', width=400)

from utils.plots import plot_results 
plot_results(save_dir='runs/train/potholeyolovfinal32')  # plot all results*.txt as results.png
Image(filename='runs/train/potholeyolovfinal32/results.png', width=400)

!python detect.py --source /content/gdrive/MyDrive/potholenew/ --img 416 --weights /content/gdrive/MyDrive/moredatayolov3/runs/train/lastmorepothole3/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes4/images/ --img 416 --weights /content/gdrive/MyDrive/moredatayolov3/runs/train/lastmorepothole3/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes4/images/ --img 416 --weights /content/gdrive/MyDrive/moredatayolov3/runs/train/lastmorepothole3/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes4/images/ --img 416 --weights /content/gdrive/MyDrive/moredatayolov3/runs/train/potholeyolovfinal32/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes3/images/test/ --img 416 --weights /content/gdrive/MyDrive/moredatayolov3/runs/train/lastmorepothole3/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes5/images3 --img 416 --weights /content/gdrive/MyDrive/moredatayolov3/runs/train/lastmorepothole3/weights/best.pt

!python detect.py --source /content/gdrive/MyDrive/potholes/images/test/ --weights /content/gdrive/MyDrive/moredatayolov3/runs/train/lastmorepothole3/weights/best.pt